AllCops:
  TargetRubyVersion: 2.6.3
  DisplayCopNames: true
  Exclude:
    - 'db/migrate/**'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'

# Disable documentations, leave it on the programmer’s conscience
Style/Documentation:
  Enabled: false

# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
Metrics/LineLength:
  Max: 120

# Configuration parameters: CountBlocks.
Metrics/BlockNesting:
  Max: 4

# Disable checking compact/nesting class/modules style
Style/ClassAndModuleChildren:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/**/*'
    - 'spec/**/*'
  Max: 120

Metrics/ClassLength:
  Max: 200

# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 15

# CyclomaticComplexity
Metrics/CyclomaticComplexity:
  Max: 15

# PerceivedComplexity
Metrics/PerceivedComplexity:
  Max: 15

# Assignment Branch condition
Metrics/AbcSize:
  Max: 30

Style/MixinUsage:
  Exclude:
    - 'bin/*'

Style/StderrPuts:
  Exclude:
    - 'bin/*'

require:
  - rubocop-rails
  - rubocop-rspec

################################## Rails ##################################
Rails:
  Enabled: true
  TargetRailsVersion: 6.0

################################## RSpec ##################################
RSpec/NestedGroups:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

# TODO: enable and correct
RSpec/ContextWording:
  Enabled: false

# TODO: enable and correct
RSpec/LeadingSubject:
  Enabled: false
