AllCops:
  TargetRailsVersion: 5.2
  TargetRubyVersion: 2.4.1
  DisplayCopNames: true
  Exclude:
    - 'db/migrate/**'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'

# Disable documentations, leave it on the programmer’s conscience
Style/Documentation:
  Enabled: false

# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
Metrics/LineLength:
  Max: 120

# Configuration parameters: CountBlocks.
Metrics/BlockNesting:
  Max: 4

# Disable checking compact/nesting class/modules style
Style/ClassAndModuleChildren:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/ClassLength:
  Max: 200

# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 15

# CyclomaticComplexity
Metrics/CyclomaticComplexity:
  Max: 15

# PerceivedComplexity
Metrics/PerceivedComplexity:
  Max: 15

# Assignment Branch condition
Metrics/AbcSize:
  Max: 30

################################## RSpec ##################################

require: rubocop-rspec

RSpec/NestedGroups:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/Focus:
  Exclude:
    - 'spec/factories/**/*'
