default: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: <%= ENV.fetch("BLOG_DATABASE_MAX_THREADS") { 5 } %>
  username: <%= ENV['BLOG_DATABASE_USERNAME'] %>
  password: <%= ENV['BLOG_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: blog_development

test:
  <<: *default
  database: blog_test

production:
  <<: *default
  database: blog_production
